### PR TITLE
updated webstorm to 9.0.2

### PR DESCRIPTION
**Pull request by digitaldrummerj**
also removed chocoaltey dependency.  this is already a chocolatey package and would be installed from chocolatey so didnt seem needed.

### CODE REVIEW

**Comment by digitaldrummerj** [comment]
ping.  any chance of getting this pull request applied?  It would be nice to have a Chocolatey package for WebStorm 9

**Comment by ferventcoder** [comment]
@derigel23 I'm not sure if you are watching this repo or not but can you take a look at this?

**Comment by digitaldrummerj** [comment]
@derigel23 really wish that Jetbrains would support a Chocolatey package for Webstorm like they do for Resharper.  Instead it looks like Jetbrains removed the Webstorm Chocolatey package from this repository.  In the meantime, I have been keeping the Chocolatey package for Webstorm up to date with the hopes that Jetbrains would once again support it.

**Comment by skyguy94** [comment]
I created/maintain the TC server one. I submitted a PR to them and got silence. I'm ok if they don't want to do it, but I was surprised and a little frustrated that they didn't communicate at all.

**Pull request closed without merging**
